# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6475-modules/motorola/include \

ifneq ($(filter m y,$(CONFIG_MMI_RELAY)),)
	EXTRA_CFLAGS += -DMMI_RELAY_MODULE
endif

ifneq ($(filter m y,$(CONFIG_GOODIX_DRM_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_GOODIX_DRM_PANEL_NOTIFICATIONS
endif

ifneq (,$(findstring banks,$(TARGET_PRODUCT)))
	EXTRA_CFLAGS += -DSOFTDEP_GPIO_PCAL6408
endif

goodix_ppg_mmi-y += gh_bus_access.o gh_common.o gh_customer.o gh_platform.o

obj-m += goodix_ppg_mmi.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_relay/$(GKI_OBJ_MODULE_DIR)/Module.symvers
